"""Fail-closed data contract for strategy-center live order candidates."""
from __future__ import annotations

import json
from datetime import datetime, timedelta
from typing import Any

from config import IS_POSTGRES
from database import engine
from db_utils import connect_stock_db


DDL = """
CREATE TABLE IF NOT EXISTS live_strategy_approvals (
    strategy_key TEXT PRIMARY KEY,
    approval_status TEXT NOT NULL DEFAULT 'blocked',
    verification_status TEXT NOT NULL DEFAULT 'legacy',
    approved_at TEXT,
    expires_at TEXT,
    approved_by TEXT NOT NULL DEFAULT '',
    evidence_uri TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS trading_restrictions (
    stock_code TEXT PRIMARY KEY,
    as_of TEXT NOT NULL,
    is_tradable INTEGER NOT NULL DEFAULT 0,
    is_halted INTEGER NOT NULL DEFAULT 0,
    is_management INTEGER NOT NULL DEFAULT 0,
    warning_level TEXT NOT NULL DEFAULT 'unknown',
    is_short_overheat INTEGER NOT NULL DEFAULT 0,
    source TEXT NOT NULL,
    raw_json TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS orderbook_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    stock_code TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    bid1 REAL NOT NULL,
    ask1 REAL NOT NULL,
    bid_qty1 REAL,
    ask_qty1 REAL,
    total_bid_qty REAL,
    total_ask_qty REAL,
    source TEXT NOT NULL,
    raw_json TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS ix_orderbook_code_time
    ON orderbook_snapshots(stock_code, observed_at);
CREATE TABLE IF NOT EXISTS broker_order_reconciliation (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    local_order_id INTEGER,
    broker_order_no TEXT NOT NULL,
    trade_date TEXT NOT NULL,
    stock_code TEXT NOT NULL,
    side TEXT NOT NULL,
    requested_qty REAL,
    filled_qty REAL NOT NULL DEFAULT 0,
    avg_fill_price REAL,
    broker_status TEXT NOT NULL,
    reconciliation_status TEXT NOT NULL,
    mismatch_reason TEXT NOT NULL DEFAULT '',
    source_payload TEXT NOT NULL DEFAULT '{}',
    reconciled_at TEXT NOT NULL,
    UNIQUE(trade_date, broker_order_no)
);
CREATE INDEX IF NOT EXISTS ix_broker_recon_local_order
    ON broker_order_reconciliation(local_order_id);
"""


def ensure_live_data_schema() -> None:
    if IS_POSTGRES:
        statements = [part.strip() for part in DDL.split(";") if part.strip()]
        with engine.begin() as conn:
            for statement in statements:
                statement = statement.replace(
                    "INTEGER PRIMARY KEY AUTOINCREMENT",
                    "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                )
                conn.exec_driver_sql(statement)
        return
    conn = connect_stock_db()
    try:
        conn.executescript(DDL)
        conn.commit()
    finally:
        conn.close()


def record_execution_snapshot(stock_code: str, quote: dict, orderbook: dict) -> None:
    """Persist broker-sourced tradability and top-of-book observations."""
    ensure_live_data_schema()
    now = str(quote.get("observed_at") or orderbook.get("observed_at") or datetime.now().isoformat())
    raw_quote = quote.get("raw") or {}
    halted = str(raw_quote.get("temp_stop_yn") or "N").upper() == "Y"
    management = str(raw_quote.get("mang_issu_cls_code") or "00").upper() not in {"", "00", "0", "N"}
    warning = str(raw_quote.get("mrkt_warn_cls_code") or "00")
    caution = str(raw_quote.get("invt_caful_yn") or "N").upper() == "Y"
    short_overheat = str(raw_quote.get("short_over_yn") or "N").upper() == "Y"
    known_restriction = all(
        key in raw_quote
        for key in ("temp_stop_yn", "mrkt_warn_cls_code", "invt_caful_yn", "short_over_yn")
    )
    is_tradable = int(known_restriction and not halted and not management and not caution and warning in {"", "00", "0"})

    conn = connect_stock_db()
    try:
        conn.execute(
            """INSERT INTO trading_restrictions(
                   stock_code,as_of,is_tradable,is_halted,is_management,warning_level,
                   is_short_overheat,source,raw_json,updated_at
               ) VALUES(?,?,?,?,?,?,?,?,?,?)
               ON CONFLICT(stock_code) DO UPDATE SET
                 as_of=excluded.as_of,is_tradable=excluded.is_tradable,
                 is_halted=excluded.is_halted,is_management=excluded.is_management,
                 warning_level=excluded.warning_level,is_short_overheat=excluded.is_short_overheat,
                 source=excluded.source,raw_json=excluded.raw_json,updated_at=excluded.updated_at""",
            (
                stock_code, now, is_tradable, int(halted), int(management), warning,
                int(short_overheat), "KIS_INQUIRE_PRICE", json.dumps(raw_quote, ensure_ascii=False), now,
            ),
        )
        bid1 = float(orderbook.get("bid1") or 0)
        ask1 = float(orderbook.get("ask1") or 0)
        if bid1 > 0 and ask1 > 0:
            conn.execute(
                """INSERT INTO orderbook_snapshots(
                     stock_code,observed_at,bid1,ask1,bid_qty1,ask_qty1,total_bid_qty,total_ask_qty,source,raw_json
                   ) VALUES(?,?,?,?,?,?,?,?,?,?)""",
                (
                    stock_code, now, bid1, ask1, orderbook.get("bid_qty1"), orderbook.get("ask_qty1"),
                    orderbook.get("total_bid_qty"), orderbook.get("total_ask_qty"), "KIS_ORDERBOOK",
                    json.dumps(orderbook.get("raw") or {}, ensure_ascii=False),
                ),
            )
        conn.commit()
    finally:
        conn.close()


def _parse_time(value: Any) -> datetime | None:
    if not value:
        return None
    text = str(value).replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(text)
        return parsed.replace(tzinfo=None) if parsed.tzinfo else parsed
    except ValueError:
        try:
            return datetime.strptime(text[:19], "%Y-%m-%d %H:%M:%S")
        except ValueError:
            return None


def evaluate_live_data_contract(
    stock_code: str,
    side: str,
    strategy_key: str | None,
    order_krw: float,
    *,
    now: datetime | None = None,
    conn=None,
) -> dict:
    """Return a candidate-level verdict. Missing evidence always blocks a buy."""
    ensure_live_data_schema()
    owned = conn is None
    conn = conn or connect_stock_db(readonly=True)
    now = now or datetime.now()
    checks: dict[str, dict] = {}
    try:
        if side == "sell":
            return {"allowed": True, "decision": "SELL_RISK_REDUCTION_ALLOWED", "checks": checks, "reasons": []}

        approval = conn.execute(
            """SELECT approval_status,verification_status,expires_at,evidence_uri
               FROM live_strategy_approvals WHERE strategy_key=?""",
            (strategy_key or "",),
        ).fetchone()
        approval_ok = bool(
            strategy_key and approval and approval[0] == "approved"
            and approval[1] == "forward_validated"
            and (not approval[2] or str(approval[2]) >= now.isoformat(timespec="seconds"))
            and approval[3]
        )
        checks["strategy_approval"] = {"ok": approval_ok, "strategy_key": strategy_key}

        restriction = conn.execute(
            """SELECT as_of,is_tradable,is_halted,is_management,warning_level,is_short_overheat,raw_json
               FROM trading_restrictions WHERE stock_code=?""",
            (stock_code,),
        ).fetchone()
        restriction_age = (now - _parse_time(restriction[0])).total_seconds() if restriction and _parse_time(restriction[0]) else None
        restriction_ok = bool(
            restriction and restriction_age is not None and restriction_age <= 300
            and int(restriction[1] or 0) == 1 and not any(int(restriction[i] or 0) for i in (2, 3, 5))
            and str(restriction[4] or "unknown") in {"", "00", "0"}
        )
        checks["tradability"] = {"ok": restriction_ok, "age_seconds": restriction_age}
        try:
            quote_raw = json.loads(restriction[6] or "{}") if restriction else {}
        except (TypeError, ValueError):
            quote_raw = {}
        intraday_turnover = float(quote_raw.get("acml_tr_pbmn") or 0)
        checks["intraday_turnover"] = {"ok": intraday_turnover > 0, "trade_amount": intraday_turnover}

        book = conn.execute(
            """SELECT observed_at,bid1,ask1,bid_qty1,ask_qty1
               FROM orderbook_snapshots WHERE stock_code=? ORDER BY observed_at DESC LIMIT 1""",
            (stock_code,),
        ).fetchone()
        book_age = (now - _parse_time(book[0])).total_seconds() if book and _parse_time(book[0]) else None
        spread_pct = ((float(book[2]) - float(book[1])) / float(book[1]) * 100) if book and float(book[1] or 0) > 0 else None
        book_ok = bool(
            book and book_age is not None and 0 <= book_age <= 15 and spread_pct is not None
            and 0 <= spread_pct <= 0.8 and float(book[3] or 0) > 0 and float(book[4] or 0) > 0
        )
        checks["orderbook"] = {"ok": book_ok, "age_seconds": book_age, "spread_pct": spread_pct}

        prices = conn.execute(
            """SELECT date,trade_amount FROM price_history
               WHERE stock_code=? AND close>0 ORDER BY date DESC LIMIT 20""",
            (stock_code,),
        ).fetchall()
        official_turnovers = [float(row[1] or 0) for row in prices if float(row[1] or 0) > 0]
        latest_age = (now.date() - datetime.fromisoformat(str(prices[0][0])[:10]).date()).days if prices else None
        adv = sum(official_turnovers) / len(official_turnovers) if official_turnovers else 0
        participation = order_krw / adv if adv > 0 else None
        liquidity_ok = bool(
            len(prices) >= 20 and len(official_turnovers) >= 15 and latest_age is not None and latest_age <= 5
            and participation is not None and participation <= 0.01
        )
        checks["official_liquidity"] = {
            "ok": liquidity_ok, "official_days": len(official_turnovers),
            "latest_age_days": latest_age, "participation": participation,
        }

        action = conn.execute(
            """SELECT COUNT(*) FROM corporate_action_events
               WHERE stock_code=? AND event_date>=?
                 AND adjustment_status NOT IN ('factor_confirmed','not_price_adjusting')""",
            (stock_code, (now.date() - timedelta(days=45)).isoformat()),
        ).fetchone()
        jumps = conn.execute(
            """SELECT COUNT(*) FROM price_jump_audit
               WHERE stock_code=? AND event_date>=? AND return_usable=0""",
            (stock_code, (now.date() - timedelta(days=550)).isoformat()),
        ).fetchone()
        recent_unconfirmed = int(action[0] or 0) if action else 0
        unusable_jumps = int(jumps[0] or 0) if jumps else 0
        checks["corporate_actions"] = {
            "ok": recent_unconfirmed == 0 and unusable_jumps == 0,
            "unconfirmed_45d": recent_unconfirmed,
            "unusable_price_jumps_550d": unusable_jumps,
        }

        dilution = conn.execute(
            """SELECT COUNT(*),COUNT(*) FILTER (WHERE issue_amount IS NULL)
               FROM dilution_events WHERE stock_code=? AND disclosed_at>=?
                 AND event_type IN ('CB','BW','EB','RIGHTS','RIGHTS_BONUS')
                 AND COALESCE(risk_amount_status,'amount_confirmed')<>'not_amount_applicable'""",
            (stock_code, (now.date() - timedelta(days=365)).isoformat()),
        ).fetchone()
        checks["dilution_completeness"] = {
            "ok": dilution is not None and int(dilution[1] or 0) == 0,
            "events_1y": int(dilution[0] or 0) if dilution else None,
            "missing_amount": int(dilution[1] or 0) if dilution else None,
        }

        failed = [name for name, result in checks.items() if not result["ok"]]
        return {
            "allowed": not failed,
            "decision": "LIVE_DATA_ALLOWED" if not failed else "BLOCKED_LIVE_DATA",
            "checks": checks,
            "reasons": failed,
        }
    finally:
        if owned:
            conn.close()
