"""Auditable cash and transaction-cost ledger for strategy-center paper trading."""
from __future__ import annotations

import os
from datetime import datetime

from config import IS_POSTGRES
from database import engine

BUY_COMMISSION_RATE = float(os.getenv("VIRTUAL_BUY_COMMISSION_RATE", "0.00015"))
SELL_COMMISSION_RATE = float(os.getenv("VIRTUAL_SELL_COMMISSION_RATE", "0.00015"))
SELL_TAX_RATE = float(os.getenv("VIRTUAL_SELL_TAX_RATE", "0.0020"))
SLIPPAGE_RATE = float(os.getenv("VIRTUAL_SLIPPAGE_RATE", "0.0005"))

DDL = """
CREATE TABLE IF NOT EXISTS virtual_cash_accounts (
 strategy TEXT PRIMARY KEY, initial_cash REAL NOT NULL, balance_krw REAL NOT NULL,
 total_fees REAL NOT NULL DEFAULT 0, total_taxes REAL NOT NULL DEFAULT 0,
 total_slippage REAL NOT NULL DEFAULT 0, realized_pnl_gross REAL NOT NULL DEFAULT 0,
 realized_pnl_net REAL NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS virtual_cash_ledger (
 id INTEGER PRIMARY KEY AUTOINCREMENT, strategy TEXT NOT NULL, event_type TEXT NOT NULL,
 stock_code TEXT, stock_name TEXT, holding_id INTEGER, quantity INTEGER NOT NULL,
 price REAL NOT NULL, gross_amount REAL NOT NULL, fee REAL NOT NULL, tax REAL NOT NULL,
 slippage_cost REAL NOT NULL, cash_delta REAL NOT NULL, balance_after REAL NOT NULL,
 realized_pnl_gross REAL NOT NULL DEFAULT 0, realized_pnl_net REAL NOT NULL DEFAULT 0,
 ref_key TEXT NOT NULL UNIQUE, occurred_at TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_virtual_cash_ledger_strategy_time
 ON virtual_cash_ledger(strategy,occurred_at);
CREATE TABLE IF NOT EXISTS virtual_position_costs (
 holding_id INTEGER PRIMARY KEY, strategy TEXT NOT NULL, stock_code TEXT, stock_name TEXT,
 buy_fee REAL NOT NULL, buy_slippage REAL NOT NULL, gross_cost REAL NOT NULL,
 opened_at TEXT NOT NULL, closed_at TEXT
);
"""
_SCHEMA_READY = False


def ensure_schema(conn=None) -> None:
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    if IS_POSTGRES:
        statements = [part.strip() for part in DDL.split(";") if part.strip()]
        with engine.begin() as db:
            for statement in statements:
                db.exec_driver_sql(statement.replace(
                    "INTEGER PRIMARY KEY AUTOINCREMENT",
                    "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                ))
        _SCHEMA_READY = True
        return
    if conn is None:
        raise ValueError("SQLite schema creation requires a connection")
    conn.executescript(DDL)
    _SCHEMA_READY = True


def initialize_account(conn, strategy: str, initial_cash: float) -> float:
    ensure_schema(conn)
    now = datetime.now().isoformat(timespec="seconds")
    conn.execute(
        """INSERT INTO virtual_cash_accounts(
             strategy,initial_cash,balance_krw,created_at,updated_at)
           VALUES(?,?,?,?,?) ON CONFLICT(strategy) DO NOTHING""",
        (strategy, initial_cash, initial_cash, now, now),
    )
    row = conn.execute(
        "SELECT balance_krw FROM virtual_cash_accounts WHERE strategy=?", (strategy,)
    ).fetchone()
    return float(row[0])


def available_cash(conn, strategy: str, initial_cash: float) -> float:
    return initialize_account(conn, strategy, initial_cash)


def record_trade(
    conn,
    *,
    strategy: str,
    initial_cash: float,
    side: str,
    stock_code: str,
    stock_name: str,
    holding_id: int | None,
    quantity: int,
    price: float,
    ref_key: str,
    occurred_at: str,
    gross_profit: float = 0.0,
) -> dict:
    """Record one idempotent paper fill and update account cash atomically."""
    side = side.lower()
    if side not in {"buy", "sell"} or quantity <= 0 or price <= 0:
        raise ValueError("valid side, positive quantity and price are required")
    existing = conn.execute(
        "SELECT balance_after,realized_pnl_net FROM virtual_cash_ledger WHERE ref_key=?",
        (ref_key,),
    ).fetchone()
    if existing:
        return {"inserted": False, "balance_after": float(existing[0]), "realized_pnl_net": float(existing[1])}

    balance = initialize_account(conn, strategy, initial_cash)
    gross = float(quantity) * float(price)
    fee = gross * (BUY_COMMISSION_RATE if side == "buy" else SELL_COMMISSION_RATE)
    tax = gross * SELL_TAX_RATE if side == "sell" else 0.0
    slippage = gross * SLIPPAGE_RATE
    buy_costs = 0.0
    if side == "sell" and holding_id is not None:
        cost = conn.execute(
            "SELECT buy_fee,buy_slippage FROM virtual_position_costs WHERE holding_id=?",
            (holding_id,),
        ).fetchone()
        if cost:
            buy_costs = float(cost[0] or 0) + float(cost[1] or 0)
    realized_net = float(gross_profit) - buy_costs - fee - tax - slippage if side == "sell" else 0.0
    cash_delta = -(gross + fee + slippage) if side == "buy" else gross - fee - tax - slippage
    balance_after = balance + cash_delta
    if balance_after < -0.5:
        raise ValueError(f"virtual cash would become negative: {balance_after:.2f}")
    now = datetime.now().isoformat(timespec="seconds")
    conn.execute(
        """INSERT INTO virtual_cash_ledger(
             strategy,event_type,stock_code,stock_name,holding_id,quantity,price,gross_amount,
             fee,tax,slippage_cost,cash_delta,balance_after,realized_pnl_gross,
             realized_pnl_net,ref_key,occurred_at,created_at)
           VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
        (
            strategy, side, stock_code or None, stock_name, holding_id, quantity, price, gross,
            fee, tax, slippage, cash_delta, balance_after,
            float(gross_profit) if side == "sell" else 0.0, realized_net,
            ref_key, occurred_at, now,
        ),
    )
    conn.execute(
        """UPDATE virtual_cash_accounts SET balance_krw=?,total_fees=total_fees+?,
             total_taxes=total_taxes+?,total_slippage=total_slippage+?,
             realized_pnl_gross=realized_pnl_gross+?,realized_pnl_net=realized_pnl_net+?,updated_at=?
           WHERE strategy=?""",
        (
            balance_after, fee, tax, slippage,
            float(gross_profit) if side == "sell" else 0.0, realized_net, now, strategy,
        ),
    )
    if side == "buy" and holding_id is not None:
        conn.execute(
            """INSERT INTO virtual_position_costs(
                 holding_id,strategy,stock_code,stock_name,buy_fee,buy_slippage,gross_cost,opened_at)
               VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(holding_id) DO UPDATE SET
                 buy_fee=excluded.buy_fee,buy_slippage=excluded.buy_slippage,
                 gross_cost=excluded.gross_cost,opened_at=excluded.opened_at""",
            (holding_id, strategy, stock_code or None, stock_name, fee, slippage, gross, occurred_at),
        )
    elif side == "sell" and holding_id is not None:
        conn.execute(
            "UPDATE virtual_position_costs SET closed_at=? WHERE holding_id=?",
            (occurred_at, holding_id),
        )
    return {
        "inserted": True, "balance_after": balance_after, "fee": fee, "tax": tax,
        "slippage_cost": slippage, "realized_pnl_net": realized_net,
    }


def account_summary(conn, strategy: str) -> dict | None:
    ensure_schema(conn)
    row = conn.execute(
        """SELECT initial_cash,balance_krw,total_fees,total_taxes,total_slippage,
                  realized_pnl_gross,realized_pnl_net,updated_at
           FROM virtual_cash_accounts WHERE strategy=?""",
        (strategy,),
    ).fetchone()
    if not row:
        return None
    keys = (
        "initial_cash", "balance_krw", "total_fees", "total_taxes", "total_slippage",
        "realized_pnl_gross", "realized_pnl_net", "updated_at",
    )
    return dict(zip(keys, row))
