from __future__ import annotations

import json
import re
import sqlite3
import time
from collections import Counter
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Query

from config import IS_POSTGRES
from db_utils import connect_stock_db

router = APIRouter()
CHERRY_CHANNEL_PREFIX = "체리형부"
ANALYST_LOOKBACK_DAYS = 365
MAX_INLINE_ANALYST_PDF_PREVIEWS = 1
_PORTFOLIO_COMPARE_CACHE: dict[int, tuple[float, dict[str, Any]]] = {}
_PORTFOLIO_COMPARE_CACHE_TTL_SEC = 300


def _today() -> datetime:
    return datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)


def _ensure_tables(conn: sqlite3.Connection) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS company_analysis_profiles (
            stock_code TEXT PRIMARY KEY,
            stock_name TEXT NOT NULL,
            source_family TEXT,
            sector_large TEXT,
            sector_mid TEXT,
            sector_small TEXT,
            value_chain_position TEXT,
            business_model TEXT,
            cycle_type TEXT,
            main_products_json TEXT,
            differentiation_json TEXT,
            bull_points_json TEXT,
            bear_points_json TEXT,
            comparison_summary TEXT,
            evidence_json TEXT,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    peer_id = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if IS_POSTGRES
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS company_peer_relations (
            {peer_id},
            stock_code TEXT NOT NULL,
            peer_code TEXT NOT NULL,
            peer_name TEXT NOT NULL,
            relation_type TEXT,
            rationale TEXT,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(stock_code, peer_code)
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS cherry_family_learning_runs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            run_type TEXT NOT NULL,
            status TEXT NOT NULL,
            started_at TEXT NOT NULL,
            completed_at TEXT,
            channels_total INTEGER DEFAULT 0,
            channels_active INTEGER DEFAULT 0,
            telegram_message_count INTEGER DEFAULT 0,
            report_file_count INTEGER DEFAULT 0,
            screener_universe_scanned INTEGER DEFAULT 0,
            three_screen_count INTEGER DEFAULT 0,
            two_screen_count INTEGER DEFAULT 0,
            portfolio_profile_count INTEGER DEFAULT 0,
            auto_candidate_count INTEGER DEFAULT 0,
            notes_json TEXT
        )
        """
    )


def _safe_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _krw_to_eok(value: Any) -> float | None:
    try:
        number = float(value)
    except Exception:
        return None
    if abs(number) >= 1_000_000:
        return round(number / 100_000_000, 1)
    return round(number, 1)


def _parse_date(value: Any) -> datetime | None:
    text = str(value or "").strip()
    if not text:
        return None
    text = text.replace("/", "-").replace(".", "-")
    text = text[:10]
    for fmt in ("%Y-%m-%d", "%y-%m-%d", "%Y-%m", "%y-%m"):
        try:
            parsed = datetime.strptime(text, fmt)
            if fmt in ("%Y-%m", "%y-%m"):
                return parsed.replace(day=1)
            return parsed
        except Exception:
            continue
    return None


def _format_date(value: datetime | None) -> str | None:
    return value.strftime("%Y-%m-%d") if value else None


def _extract_embedded_dates(text: str) -> list[datetime]:
    found: list[datetime] = []
    for match in re.finditer(r"(?<!\d)(20\d{2})[._-]?(\d{1,2})[._-]?(\d{1,2})(?!\d)", text):
        try:
            found.append(datetime(int(match.group(1)), int(match.group(2)), int(match.group(3))))
        except Exception:
            continue
    for match in re.finditer(r"(?<!\d)(\d{2})(\d{2})(\d{2})(?!\d)", text):
        year = int(match.group(1))
        if year > 40:
            continue
        try:
            found.append(datetime(2000 + year, int(match.group(2)), int(match.group(3))))
        except Exception:
            continue
    return found


def _parse_channel_window(channel_name: str) -> tuple[datetime | None, datetime | None]:
    text = str(channel_name or "")
    bracket = re.search(
        r"\[(\d{2})\.(\d{1,2})\.(\d{1,2})\s*~\s*(\d{2})\.(\d{1,2})\.(\d{1,2})\]",
        text,
    )
    if bracket:
        return (
            datetime(2000 + int(bracket.group(1)), int(bracket.group(2)), int(bracket.group(3))),
            datetime(2000 + int(bracket.group(4)), int(bracket.group(5)), int(bracket.group(6))),
        )
    loose = re.search(r"(20\d{2})\.(\d{1,2})\.(\d{1,2})~(\d{1,2})\.(\d{1,2})", text)
    if loose:
        year = int(loose.group(1))
        start = datetime(year, int(loose.group(2)), int(loose.group(3)))
        end_month = int(loose.group(4))
        end_day = int(loose.group(5))
        end_year = year if end_month >= start.month else year + 1
        return start, datetime(end_year, end_month, end_day)
    return None, None


def _channel_period_label(channel_name: str) -> str:
    text = str(channel_name or "")
    quarter_match = re.search(r"(25\.4Q|26\.1Q|26\.2Q|26\.3Q|26\.4Q)", text)
    if quarter_match:
        return quarter_match.group(1)
    if "26.06.01~08.31" in text:
        return "26.06~08"
    return text or "기타"


def _is_cherry_channel(channel_name: str) -> bool:
    text = str(channel_name or "")
    return text.startswith(CHERRY_CHANNEL_PREFIX) or "Valuefs" in text or "체리형부" in text


def _pick_best_date(
    report_date: Any,
    posted_date: Any,
    created_at: Any,
    channel_name: str,
    file_name: str,
    caption: str,
) -> dict[str, Any]:
    start, end = _parse_channel_window(channel_name)
    candidates: list[tuple[datetime, str, int]] = []
    base_candidates = [
        (_parse_date(report_date), "report_date", 2),
        (_parse_date(posted_date), "posted_date", 3),
        (_parse_date(created_at), "created_at", 3),
    ]
    for dt, source, base_score in base_candidates:
        if dt:
            score = base_score
            if start and end and start <= dt <= end:
                score += 5
            elif dt.year < 2024 or dt > _today():
                score -= 3
            candidates.append((dt, source, score))
    for embedded in _extract_embedded_dates(f"{file_name} {caption}"):
        score = 1
        if start and end and start <= embedded <= end:
            score += 6
        elif embedded.year < 2024 or embedded > _today():
            score -= 2
        candidates.append((embedded, "embedded_text", score))
    if not candidates:
        return {
            "normalized_date": None,
            "date_source": None,
            "date_confidence": "low",
            "date_in_channel_window": False,
            "raw_report_date": report_date,
        }
    best_dt, best_source, best_score = max(candidates, key=lambda item: (item[2], item[0]))
    in_window = bool(start and end and start <= best_dt <= end)
    confidence = "high" if best_score >= 6 else "medium" if best_score >= 3 else "low"
    return {
        "normalized_date": _format_date(best_dt),
        "date_source": best_source,
        "date_confidence": confidence,
        "date_in_channel_window": in_window,
        "raw_report_date": report_date,
    }


def _focus_tags(text_pool: list[str]) -> list[str]:
    joined = " \n ".join(text_pool).lower()
    rules = [
        ("수주", "수주"),
        ("매출", "매출"),
        ("밸류", "밸류"),
        ("psr", "밸류"),
        ("프로브카드", "프로브카드"),
        ("소켓", "소켓"),
        ("d램", "메모리"),
        ("dram", "메모리"),
        ("gpu", "AI/GPU"),
        ("원가", "원가"),
        ("리스크", "리스크"),
        ("재고", "재고"),
        ("ir", "IR"),
        ("계약", "계약"),
    ]
    tags: list[str] = []
    for needle, tag in rules:
        if needle in joined and tag not in tags:
            tags.append(tag)
    return tags[:6]


def _load_stock_row(conn: sqlite3.Connection, stock_code: str) -> sqlite3.Row | None:
    return conn.execute(
        """
        SELECT stock_code, stock_name, market, market_cap, sector_large, sector_mid, sector_small
        FROM stock_universe
        WHERE stock_code=?
        ORDER BY base_date DESC
        LIMIT 1
        """,
        (stock_code,),
    ).fetchone()


def _load_recent_financial_snapshot(conn: sqlite3.Connection, stock_code: str) -> dict[str, Any]:
    row = conn.execute(
        """
        SELECT year, quarter, revenue, operating_profit, net_income
        FROM financial_data
        WHERE stock_code=? AND is_annual=0 AND report_type='CFS'
        ORDER BY year DESC, quarter DESC
        LIMIT 1
        """,
        (stock_code,),
    ).fetchone()
    if not row:
        return {}
    return {
        "year": int(row["year"]),
        "quarter": int(row["quarter"]),
        "revenue_억": _krw_to_eok(row["revenue"]),
        "operating_profit_억": _krw_to_eok(row["operating_profit"]),
        "net_income_억": _krw_to_eok(row["net_income"]),
    }


def _load_latest_price(conn: sqlite3.Connection, stock_code: str) -> dict[str, Any]:
    row = conn.execute(
        """
        SELECT date, close
        FROM price_history
        WHERE stock_code=? AND close IS NOT NULL
        ORDER BY date DESC
        LIMIT 1
        """,
        (stock_code,),
    ).fetchone()
    if not row:
        return {}
    return {
        "date": row["date"],
        "close": float(row["close"]) if row["close"] is not None else None,
    }


def _load_price_on_or_before(conn: sqlite3.Connection, stock_code: str, as_of: str) -> float | None:
    row = conn.execute(
        """
        SELECT close
        FROM price_history
        WHERE stock_code=? AND date<=? AND close IS NOT NULL
        ORDER BY date DESC
        LIMIT 1
        """,
        (stock_code, as_of),
    ).fetchone()
    if not row or row["close"] is None:
        return None
    return float(row["close"])


def _load_text_evidence(
    conn: sqlite3.Connection,
    stock_code: str,
    stock_name: str,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[str], dict[str, Any], list[dict[str, Any]]]:
    report_rows = conn.execute(
        """
        SELECT channel_id, report_date, posted_date, created_at, file_name, caption
        FROM report_files
        WHERE stock_code=? OR stock_name=? OR file_name LIKE '%' || ? || '%'
        ORDER BY COALESCE(report_date, created_at) DESC, id DESC
        LIMIT 80
        """,
        (stock_code, stock_name, stock_name),
    ).fetchall()
    message_rows = conn.execute(
        """
        SELECT date, channel, text
        FROM telegram_messages
        WHERE stocks LIKE '%' || ? || '%' OR text LIKE '%' || ? || '%'
        ORDER BY date DESC
        LIMIT 120
        """,
        (stock_name, stock_name),
    ).fetchall()
    reports = []
    messages = []
    text_pool: list[str] = []
    cherry_timeline: dict[str, dict[str, Any]] = {}
    invalid_report_dates = 0
    normalized_report_dates = 0
    for row in report_rows:
        caption = str(row["caption"] or "").replace("\n", " ").strip()
        file_name = str(row["file_name"] or "")
        channel_name = str(row["channel_id"] or "")
        date_meta = _pick_best_date(
            row["report_date"],
            row["posted_date"],
            row["created_at"],
            channel_name,
            file_name,
            caption,
        )
        reports.append(
            {
                "date": date_meta["normalized_date"] or row["report_date"],
                "raw_report_date": row["report_date"],
                "file_name": file_name,
                "caption": caption[:180],
                "channel": channel_name,
                "date_source": date_meta["date_source"],
                "date_confidence": date_meta["date_confidence"],
                "date_in_channel_window": date_meta["date_in_channel_window"],
            }
        )
        text_pool.append(file_name)
        if caption:
            text_pool.append(caption)
        if row["report_date"] and date_meta["normalized_date"] and str(row["report_date"]) != str(date_meta["normalized_date"]):
            normalized_report_dates += 1
        if row["report_date"] and not date_meta["date_in_channel_window"] and _is_cherry_channel(channel_name):
            invalid_report_dates += 1
        if _is_cherry_channel(channel_name):
            bucket = _channel_period_label(channel_name)
            entry = cherry_timeline.setdefault(
                bucket,
                {
                    "period": bucket,
                    "channel": channel_name,
                    "reports_count": 0,
                    "messages_count": 0,
                    "keywords": Counter(),
                    "focus_tags": [],
                    "sample_dates": [],
                    "window_start": _format_date(_parse_channel_window(channel_name)[0]),
                },
            )
            entry["reports_count"] += 1
            if date_meta["normalized_date"] and len(entry["sample_dates"]) < 3:
                entry["sample_dates"].append(date_meta["normalized_date"])
            for token in _keyword_summary([file_name, caption]):
                entry["keywords"][token] += 1
            for tag in _focus_tags([file_name, caption]):
                if tag not in entry["focus_tags"]:
                    entry["focus_tags"].append(tag)
    for row in message_rows:
        text = str(row["text"] or "").replace("\n", " ").strip()
        messages.append({"date": row["date"], "channel": row["channel"], "text": text[:220]})
        if text:
            text_pool.append(text)
        if _is_cherry_channel(str(row["channel"] or "")):
            bucket = _channel_period_label(str(row["channel"] or ""))
            entry = cherry_timeline.setdefault(
                bucket,
                {
                    "period": bucket,
                    "channel": str(row["channel"] or ""),
                    "reports_count": 0,
                    "messages_count": 0,
                    "keywords": Counter(),
                    "focus_tags": [],
                    "sample_dates": [],
                    "window_start": _format_date(_parse_channel_window(str(row["channel"] or ""))[0]),
                },
            )
            entry["messages_count"] += 1
            for token in _keyword_summary([text]):
                entry["keywords"][token] += 1
            for tag in _focus_tags([text]):
                if tag not in entry["focus_tags"]:
                    entry["focus_tags"].append(tag)
    timeline = []
    for _, item in sorted(cherry_timeline.items(), key=lambda pair: pair[1].get("window_start") or "9999-12-31"):
        timeline.append(
            {
                "period": item["period"],
                "channel": item["channel"],
                "reports_count": item["reports_count"],
                "messages_count": item["messages_count"],
                "top_keywords": [token for token, _ in item["keywords"].most_common(6)],
                "focus_tags": item["focus_tags"][:5],
                "sample_dates": item["sample_dates"][:3],
            }
        )
    date_quality = {
        "report_count": len(reports),
        "normalized_report_dates": normalized_report_dates,
        "suspect_cherry_report_dates": invalid_report_dates,
        "message_count": len(messages),
    }
    return reports, messages, text_pool, date_quality, timeline


def _classify_from_text(text_pool: list[str]) -> dict[str, Any]:
    joined = " \n ".join(text_pool)

    product_rules = [
        ("프로브카드", "프로브카드"),
        ("probe card", "프로브카드"),
        ("소켓", "테스트 소켓"),
        ("socket", "테스트 소켓"),
        ("보드", "테스트 보드"),
        ("handler", "핸들러"),
        ("d램", "D램 노출"),
        ("dram", "D램 노출"),
        ("비메모리", "비메모리 노출"),
        ("hbm", "HBM 연계"),
        ("웨이퍼", "웨이퍼 테스트"),
    ]
    main_products = []
    for needle, label in product_rules:
        if needle.lower() in joined.lower() and label not in main_products:
            main_products.append(label)

    value_chain_position = ""
    if "프로브카드" in main_products:
        value_chain_position = "웨이퍼 테스트 소모품/인터페이스"
    elif "테스트 소켓" in main_products:
        value_chain_position = "패키지 테스트 소켓/인터페이스"
    elif "테스트 보드" in main_products:
        value_chain_position = "테스트 인터페이스/보드"

    business_model = ""
    if "소모품" in joined:
        business_model = "반복 교체형 소모품 비중"
    elif "장비" in joined:
        business_model = "장비·설비투자 민감형"
    elif "부품" in joined:
        business_model = "부품/인터페이스 공급형"

    cycle_type = ""
    if "P.Q 혼합싸이클" in joined or "P/Q 혼합" in joined:
        cycle_type = "P·Q 혼합"
    elif "P싸이클" in joined:
        cycle_type = "P싸이클"
    elif "Q싸이클" in joined:
        cycle_type = "Q싸이클"

    differentiations = []
    if "신규 수주" in joined:
        differentiations.append("신규 수주 모멘텀")
    if "ir book" in joined.lower():
        differentiations.append("IR 자료 근거 풍부")
    if "확장성" in joined:
        differentiations.append("확장성 논리 반복 등장")
    if "d램" in joined.lower():
        differentiations.append("D램/메모리 업황 연동")
    if "gpu" in joined.lower():
        differentiations.append("AI/GPU 인프라 노출")

    bull_points = []
    bear_points = []
    if "매출" in joined and ("최대" in joined or "성장" in joined):
        bull_points.append("매출 성장/최고치 논리 점검 가치")
    if "수주" in joined:
        bull_points.append("수주·선행지표 연결 관찰 가능")
    if "밸류에이션" in joined or "psr" in joined.lower():
        bull_points.append("밸류에이션 비교 논리가 자주 등장")
    if "고평가" in joined:
        bear_points.append("밸류 부담 구간 논의 가능성")
    if "원가" in joined or "리스크" in joined:
        bear_points.append("원가·수익성 리스크 동반 점검 필요")

    return {
        "value_chain_position": value_chain_position,
        "business_model": business_model,
        "cycle_type": cycle_type,
        "main_products": main_products[:6],
        "differentiations": differentiations[:6],
        "bull_points": bull_points[:5],
        "bear_points": bear_points[:5],
    }


def _keyword_summary(text_pool: list[str]) -> list[str]:
    korean_tokens = Counter()
    stop = {"티에스이", "티에프이", "체리형부", "종합분석", "보고서", "ir", "book", "pdf"}
    for text in text_pool:
        for token in str(text).replace("/", " ").replace(",", " ").split():
            token = token.strip("[]()_-.·:;\"'").lower()
            if len(token) < 2 or token in stop:
                continue
            if any(ch.isdigit() for ch in token) and len(token) > 8:
                continue
            korean_tokens[token] += 1
    return [token for token, _ in korean_tokens.most_common(12)]


def _build_period_comparison_summary(timeline: list[dict[str, Any]]) -> str:
    if not timeline:
        return ""
    parts = []
    for item in timeline[:3]:
        tags = ", ".join(item.get("focus_tags") or item.get("top_keywords")[:3])
        if not tags:
            continue
        parts.append(f"{item['period']}에는 {tags} 논점이 상대적으로 많이 등장했다.")
    return " ".join(parts[:3])


def _latest_date_text(values: list[Any]) -> str | None:
    latest: datetime | None = None
    for value in values:
        parsed = _parse_date(value)
        if parsed and (latest is None or parsed > latest):
            latest = parsed
    return _format_date(latest)


def _extract_analysis_as_of(intel: dict[str, Any]) -> str | None:
    analyst_view = intel.get("analyst_view") or {}
    candidates: list[Any] = [intel.get("price_date")]
    for row in intel.get("learning_timeline") or []:
        candidates.append(row.get("normalized_date"))
    for row in analyst_view.get("latest_reports") or []:
        candidates.append(row.get("report_date"))
    for row in analyst_view.get("one_year_reports") or []:
        candidates.append(row.get("report_date"))
    return _latest_date_text(candidates)


def _opinion_bucket(opinion: str) -> str:
    value = str(opinion or "").strip().lower()
    if value in {"매수", "buy", "strong buy", "적극매수", "강력매수"}:
        return "buy"
    if value in {"매도", "sell", "underperform", "비중축소"}:
        return "sell"
    if value:
        return "hold"
    return "unknown"


def _summarize_analyst_texts(texts: list[str]) -> dict[str, Any]:
    positive_rules = [
        ("성장", "성장"),
        ("turnaround", "턴어라운드"),
        ("턴어라운드", "턴어라운드"),
        ("수주", "수주"),
        ("회복", "회복"),
        ("확대", "확대"),
        ("신제품", "신제품"),
        ("고성장", "고성장"),
    ]
    risk_rules = [
        ("리스크", "리스크"),
        ("원가", "원가"),
        ("부담", "부담"),
        ("둔화", "둔화"),
        ("변동성", "변동성"),
        ("경쟁", "경쟁"),
        ("재고", "재고"),
        ("고평가", "고평가"),
    ]
    positives = Counter()
    risks = Counter()
    for text in texts:
        lowered = str(text or "").lower()
        for needle, label in positive_rules:
            if needle in lowered:
                positives[label] += 1
        for needle, label in risk_rules:
            if needle in lowered:
                risks[label] += 1
    return {
        "positive_themes": [token for token, _ in positives.most_common(5)],
        "risk_themes": [token for token, _ in risks.most_common(5)],
    }


def _looks_like_analyst_channel(channel_name: str) -> bool:
    text = str(channel_name or "")
    if not text or _is_cherry_channel(text):
        return False
    hints = ["DOC_POOL", "선진짱", "sunstudy", "yigreport", "증권", "리포트"]
    return any(hint.lower() in text.lower() for hint in hints)


def _extract_local_pdf_preview(file_path: str, max_pages: int = 2, max_chars: int = 3000) -> str:
    path = Path(file_path or "")
    if not path.exists() or path.suffix.lower() != ".pdf":
        return ""
    try:
        import pdfplumber

        parts: list[str] = []
        with pdfplumber.open(path) as pdf:
            for page in pdf.pages[:max_pages]:
                text = page.extract_text() or ""
                if text:
                    parts.append(text)
                if sum(len(x) for x in parts) >= max_chars:
                    break
        return "\n".join(parts)[:max_chars]
    except Exception:
        return ""


def _load_analyst_report_corpus(conn: sqlite3.Connection, stock_code: str, stock_name: str) -> dict[str, Any]:
    cutoff = (_today() - timedelta(days=ANALYST_LOOKBACK_DAYS)).strftime("%Y-%m-%d")
    report_rows = conn.execute(
        """
        SELECT id, channel_id, report_date, file_name, file_path, caption
        FROM report_files
        WHERE COALESCE(report_date, created_at) >= ?
          AND (
            stock_code=?
            OR stock_name=?
            OR file_name LIKE '%' || ? || '%'
            OR caption LIKE '%' || ? || '%'
          )
        ORDER BY COALESCE(report_date, created_at) DESC, id DESC
        LIMIT 60
        """,
        (cutoff, stock_code, stock_name, stock_name, stock_name),
    ).fetchall()
    extracts = {
        int(row["report_id"]): str(row["raw_text"] or "")
        for row in conn.execute(
            """
            SELECT report_id, raw_text
            FROM analyst_pdf_extracts
            WHERE stock_code=?
            """,
            (stock_code,),
        ).fetchall()
    }
    report_titles = []
    read_texts = []
    raw_reports = []
    direct_read_count = 0
    for row in report_rows:
        channel_name = str(row["channel_id"] or "")
        if not _looks_like_analyst_channel(channel_name):
            continue
        file_name = str(row["file_name"] or "")
        preview = extracts.get(int(row["id"])) or ""
        if (
            not preview
            and direct_read_count < MAX_INLINE_ANALYST_PDF_PREVIEWS
            and str(row["file_path"] or "").lower().endswith(".pdf")
        ):
            preview = _extract_local_pdf_preview(str(row["file_path"] or ""))
        if preview:
            direct_read_count += 1
            read_texts.append(preview)
        report_titles.append(file_name)
        raw_reports.append(
            {
                "report_id": row["id"],
                "report_date": row["report_date"],
                "channel_id": channel_name,
                "file_name": file_name,
                "has_text_preview": bool(preview),
            }
        )
    theme_summary = _summarize_analyst_texts(report_titles + read_texts)
    return {
        "lookback_start": cutoff,
        "report_files_count": len(raw_reports),
        "report_files_read_count": len(raw_reports) if raw_reports else direct_read_count,
        "reports": raw_reports[:15],
        "titles": report_titles[:20],
        "themes": theme_summary,
    }


def _load_analyst_view(conn: sqlite3.Connection, stock_code: str) -> dict[str, Any]:
    stock_row = _load_stock_row(conn, stock_code)
    stock_name = stock_row["stock_name"] if stock_row else stock_code
    latest_price = _load_latest_price(conn, stock_code).get("close")
    consensus_rows = conn.execute(
        """
        WITH ranked AS (
            SELECT id, report_date, securities_firm, analyst, opinion, target_price, prev_target_price, report_title,
                   ROW_NUMBER() OVER (
                       PARTITION BY stock_code || '|' || report_date || '|' ||
                                    TRIM(COALESCE(securities_firm, '')) || '|' ||
                                    TRIM(COALESCE(analyst, '')) || '|' ||
                                    COALESCE(CAST(target_price AS TEXT), '')
                       ORDER BY id DESC
                   ) AS rn
            FROM consensus_targets
            WHERE stock_code=? AND target_price > 0
              AND report_date >= '2025-01-01'
        )
        SELECT report_date, securities_firm, analyst, opinion, target_price, prev_target_price, report_title
        FROM ranked
        WHERE rn=1
        ORDER BY report_date DESC, target_price DESC
        LIMIT 24
        """,
        (stock_code,),
    ).fetchall()
    extract_rows = conn.execute(
        """
        SELECT e.report_id, e.target_price, e.opinion, e.fwd_eps_1y, e.fwd_rev_1y, e.fwd_per,
               e.raw_text, r.file_name, r.report_date, r.channel_id
        FROM analyst_pdf_extracts e
        JOIN report_files r ON r.id = e.report_id
        WHERE e.stock_code=?
        ORDER BY COALESCE(r.report_date, e.extracted_at) DESC
        LIMIT 12
        """,
        (stock_code,),
    ).fetchall()
    report_corpus = _load_analyst_report_corpus(conn, stock_code, stock_name)
    target_prices = [float(r["target_price"]) for r in consensus_rows if r["target_price"] is not None]
    opinion_counter = Counter(_opinion_bucket(str(r["opinion"] or "")) for r in consensus_rows if r["opinion"])
    houses = []
    for row in consensus_rows[:8]:
        label = str(row["securities_firm"] or "").strip()
        if label and label not in houses:
            houses.append(label)
    report_texts = [str(r["raw_text"] or "") for r in extract_rows if str(r["raw_text"] or "").strip()]
    theme_summary = _summarize_analyst_texts(report_texts + (report_corpus.get("titles") or []))
    merged_positive = []
    for label in (theme_summary.get("positive_themes") or []) + (report_corpus.get("themes", {}).get("positive_themes") or []):
        if label not in merged_positive:
            merged_positive.append(label)
    merged_risk = []
    for label in (theme_summary.get("risk_themes") or []) + (report_corpus.get("themes", {}).get("risk_themes") or []):
        if label not in merged_risk:
            merged_risk.append(label)
    latest_reports = []
    quarter_counter = Counter()
    target_changes = Counter()
    sentiment_counter = Counter()
    for row in consensus_rows[:8]:
        title = str(row["report_title"] or "")
        tags = []
        target_price = float(row["target_price"]) if row["target_price"] is not None else None
        prev_target = float(row["prev_target_price"]) if row["prev_target_price"] is not None else None
        if target_price and prev_target:
            if target_price > prev_target:
                tags.append("목표가 상향")
                target_changes["up"] += 1
            elif target_price < prev_target:
                tags.append("목표가 하향")
                target_changes["down"] += 1
        if "유상증자" in title:
            tags.append("자금조달 이슈")
            sentiment_counter["risk"] += 1
        if "저평가" in title:
            tags.append("밸류 부각")
            sentiment_counter["positive"] += 1
        if "흑자 전환" in title or "턴어라운드" in title:
            tags.append("턴어라운드")
            sentiment_counter["positive"] += 1
        if "모멘텀" in title or "회복" in title:
            tags.append("모멘텀")
            sentiment_counter["positive"] += 1
        if "관건" in title or "고군분투" in title or "정정공시" in title:
            tags.append("리스크 점검")
            sentiment_counter["risk"] += 1
        report_date = str(row["report_date"] or "")
        q_label = None
        dt = _parse_date(report_date)
        if dt:
            quarter = (dt.month - 1) // 3 + 1
            q_label = f"{dt.year}Q{quarter}"
            quarter_counter[q_label] += 1
        ref_price = _load_price_on_or_before(conn, stock_code, report_date) if report_date else None
        current_gap_pct = None
        if latest_price and ref_price:
            try:
                current_gap_pct = round((float(latest_price) - float(ref_price)) / float(ref_price) * 100, 1)
            except Exception:
                current_gap_pct = None
        latest_reports.append(
            {
                "report_date": row["report_date"],
                "securities_firm": row["securities_firm"],
                "analyst": row["analyst"],
                "opinion": row["opinion"],
                "target_price": row["target_price"],
                "report_title": row["report_title"],
                "timeline_tags": tags[:3],
                "quarter_label": q_label,
                "reference_price": ref_price,
                "current_gap_pct": current_gap_pct,
            }
        )
    quarter_trend = []
    for quarter, count in sorted(quarter_counter.items()):
        quarter_trend.append({"quarter": quarter, "reports": count})
    trend_summary_parts = []
    if target_changes.get("up", 0) > target_changes.get("down", 0):
        trend_summary_parts.append("목표가 상향 리포트가 더 많았다.")
    elif target_changes.get("down", 0) > target_changes.get("up", 0):
        trend_summary_parts.append("목표가 하향/보수화 흐름이 더 많았다.")
    if sentiment_counter.get("positive", 0) > sentiment_counter.get("risk", 0):
        trend_summary_parts.append("최근 논조는 회복·저평가 쪽이 우세했다.")
    elif sentiment_counter.get("risk", 0) > 0:
        trend_summary_parts.append("최근 논조에는 자금조달·리스크 점검이 자주 등장했다.")
    return {
        "consensus_count": len(consensus_rows),
        "extract_count": len(extract_rows),
        "one_year_report_count": report_corpus.get("report_files_count", 0),
        "one_year_report_read_count": report_corpus.get("report_files_read_count", 0),
        "lookback_start": report_corpus.get("lookback_start"),
        "avg_target_price": round(sum(target_prices) / len(target_prices)) if target_prices else None,
        "max_target_price": round(max(target_prices)) if target_prices else None,
        "min_target_price": round(min(target_prices)) if target_prices else None,
        "opinion_distribution": {
            "buy": opinion_counter.get("buy", 0),
            "hold": opinion_counter.get("hold", 0),
            "sell": opinion_counter.get("sell", 0),
        },
        "houses": houses[:6],
        "positive_themes": merged_positive[:6],
        "risk_themes": merged_risk[:6],
        "latest_reports": latest_reports[:6],
        "quarter_trend": quarter_trend,
        "trend_summary": " ".join(trend_summary_parts[:2]),
        "extract_reports": [
            {
                "report_id": row["report_id"],
                "report_date": row["report_date"],
                "file_name": row["file_name"],
                "channel_id": row["channel_id"],
                "target_price": row["target_price"],
                "opinion": row["opinion"],
                "fwd_per": row["fwd_per"],
            }
            for row in extract_rows[:6]
        ],
        "one_year_reports": report_corpus.get("reports", []),
    }


def _build_viewpoint_comparison(profile: dict[str, Any], analyst_view: dict[str, Any]) -> dict[str, Any]:
    cherry_focus = []
    if profile.get("main_products"):
        cherry_focus.append("제품/밸류체인")
    if profile.get("bull_points"):
        cherry_focus.append("상승 논리")
    if profile.get("bear_points"):
        cherry_focus.append("리스크 점검")
    analyst_focus = []
    if analyst_view.get("positive_themes"):
        analyst_focus.append("실적 성장")
    if analyst_view.get("risk_themes"):
        analyst_focus.append("실적 리스크")
    if analyst_view.get("avg_target_price") is not None:
        analyst_focus.append("목표주가")
    overlap = []
    if any("수주" in point for point in profile.get("bull_points", [])) and "수주" in analyst_view.get("positive_themes", []):
        overlap.append("수주/선행 성장")
    if any("매출" in point for point in profile.get("bull_points", [])) and "성장" in analyst_view.get("positive_themes", []):
        overlap.append("매출 성장")
    if any("리스크" in point or "원가" in point for point in profile.get("bear_points", [])) and analyst_view.get("risk_themes"):
        overlap.append("리스크 병기")
    differences = []
    if profile.get("value_chain_position"):
        differences.append("체리형부식은 밸류체인 포지션을 더 먼저 본다.")
    if analyst_view.get("avg_target_price") is not None:
        differences.append("애널리스트는 목표주가와 실적 추정치를 더 명시적으로 제시한다.")
    return {
        "cherry_focus": cherry_focus,
        "analyst_focus": analyst_focus,
        "overlap_points": overlap[:4],
        "difference_points": differences[:4],
    }


def _build_joint_verdict(profile: dict[str, Any], analyst_view: dict[str, Any]) -> dict[str, Any]:
    bull_points = profile.get("bull_points") or []
    bear_points = profile.get("bear_points") or []
    positive_themes = analyst_view.get("positive_themes") or []
    risk_themes = analyst_view.get("risk_themes") or []
    cherry_strength = len(bull_points)
    cherry_risk = len(bear_points)
    analyst_positive = len(positive_themes)
    analyst_risk = len(risk_themes)
    avg_target = analyst_view.get("avg_target_price")
    stance = "중립"
    if cherry_strength >= 2 and analyst_positive >= analyst_risk:
        stance = "긍정"
    if cherry_risk >= 2 and analyst_risk > analyst_positive:
        stance = "보수"
    cherry_sentence = (
        (bull_points[0] if bull_points else None)
        or profile.get("comparison_summary")
        or "체리형부식 핵심 논리 정리 중"
    )
    analyst_sentence = (
        analyst_view.get("trend_summary")
        or (positive_themes[0] if positive_themes else None)
        or "애널리스트 논조 집계 중"
    )
    joint = f"체리형부식은 '{cherry_sentence}'를 먼저 보고, 애널리스트는 '{analyst_sentence}' 쪽에 무게를 둔다."
    if stance == "긍정" and avg_target is not None:
        joint += " 두 관점 모두 현재보다 상방 논리를 확인하는 흐름이다."
    elif stance == "보수":
        joint += " 다만 최근 리스크 점검 비중이 커 보수적으로 해석할 필요가 있다."
    return {
        "stance": stance,
        "cherry_summary": cherry_sentence,
        "analyst_summary": analyst_sentence,
        "joint_summary": joint,
    }


def _build_peer_rows(conn: sqlite3.Connection, stock_row: sqlite3.Row) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT stock_code, stock_name, market_cap
        FROM stock_universe
        WHERE sector_small=? AND stock_code!=?
        ORDER BY base_date DESC, market_cap DESC
        LIMIT 12
        """,
        (stock_row["sector_small"], stock_row["stock_code"]),
    ).fetchall()
    peers = []
    seen = set()
    for row in rows:
        if row["stock_code"] in seen:
            continue
        seen.add(row["stock_code"])
        peers.append(
            {
                "stock_code": row["stock_code"],
                "stock_name": row["stock_name"],
                "market_cap_억": round(float(row["market_cap"] or 0), 1) if row["market_cap"] is not None else None,
                "relation_type": "same_sector_small",
                "rationale": f"{stock_row['sector_small']} 내 비교군",
            }
        )
    return peers[:6]


def _build_comparison_summary(stock_row: sqlite3.Row, profile: dict[str, Any], peers: list[dict[str, Any]]) -> str:
    parts = []
    if profile.get("value_chain_position"):
        parts.append(f"{stock_row['stock_name']}는 {profile['value_chain_position']} 포지션으로 분류된다.")
    if profile.get("cycle_type"):
        parts.append(f"채널 문맥상 {profile['cycle_type']} 성격으로 해석되는 흔적이 있다.")
    if peers:
        peer_names = ", ".join(p["stock_name"] for p in peers[:3])
        parts.append(f"동일 세부업종 비교군은 {peer_names} 등이다.")
    return " ".join(parts)


def _persist_profile(conn: sqlite3.Connection, stock_row: sqlite3.Row, profile: dict[str, Any], peers: list[dict[str, Any]], evidence: dict[str, Any]) -> None:
    try:
        _ensure_tables(conn)
        conn.execute(
            """
            INSERT INTO company_analysis_profiles (
                stock_code, stock_name, source_family, sector_large, sector_mid, sector_small,
                value_chain_position, business_model, cycle_type, main_products_json,
                differentiation_json, bull_points_json, bear_points_json, comparison_summary,
                evidence_json, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(stock_code) DO UPDATE SET
                stock_name=excluded.stock_name,
                source_family=excluded.source_family,
                sector_large=excluded.sector_large,
                sector_mid=excluded.sector_mid,
                sector_small=excluded.sector_small,
                value_chain_position=excluded.value_chain_position,
                business_model=excluded.business_model,
                cycle_type=excluded.cycle_type,
                main_products_json=excluded.main_products_json,
                differentiation_json=excluded.differentiation_json,
                bull_points_json=excluded.bull_points_json,
                bear_points_json=excluded.bear_points_json,
                comparison_summary=excluded.comparison_summary,
                evidence_json=excluded.evidence_json,
                updated_at=excluded.updated_at
            """,
            (
                stock_row["stock_code"],
                stock_row["stock_name"],
                "cherry_source_family",
                stock_row["sector_large"],
                stock_row["sector_mid"],
                stock_row["sector_small"],
                profile.get("value_chain_position"),
                profile.get("business_model"),
                profile.get("cycle_type"),
                _safe_json(profile.get("main_products", [])),
                _safe_json(profile.get("differentiations", [])),
                _safe_json(profile.get("bull_points", [])),
                _safe_json(profile.get("bear_points", [])),
                profile.get("comparison_summary"),
                _safe_json(evidence),
                datetime.now().isoformat(),
            ),
        )
        conn.execute("DELETE FROM company_peer_relations WHERE stock_code=?", (stock_row["stock_code"],))
        for peer in peers:
            conn.execute(
                """
                INSERT INTO company_peer_relations
                (stock_code, peer_code, peer_name, relation_type, rationale, updated_at)
                VALUES (?, ?, ?, ?, ?, ?)
                ON CONFLICT(stock_code, peer_code) DO UPDATE SET
                    peer_name=excluded.peer_name,
                    relation_type=excluded.relation_type,
                    rationale=excluded.rationale,
                    updated_at=excluded.updated_at
                """,
                (
                    stock_row["stock_code"],
                    peer["stock_code"],
                    peer["stock_name"],
                    peer["relation_type"],
                    peer["rationale"],
                    datetime.now().isoformat(),
                ),
            )
        conn.commit()
    except Exception:
        conn.rollback()


def _compute_company_intelligence(conn: sqlite3.Connection, stock_code: str) -> dict[str, Any]:
    stock_row = _load_stock_row(conn, stock_code)
    if not stock_row:
        return {"stock_code": stock_code, "found": False}

    financial = _load_recent_financial_snapshot(conn, stock_code)
    latest_price = _load_latest_price(conn, stock_code)
    reports, messages, text_pool, date_quality, learning_timeline = _load_text_evidence(conn, stock_code, stock_row["stock_name"])
    inferred = _classify_from_text(text_pool)
    keywords = _keyword_summary(text_pool)
    peers = _build_peer_rows(conn, stock_row)
    analyst_view = _load_analyst_view(conn, stock_code)

    profile = {
        **inferred,
        "comparison_summary": _build_comparison_summary(stock_row, inferred, peers),
        "period_comparison_summary": _build_period_comparison_summary(learning_timeline),
    }
    evidence = {
        "reports": reports[:8],
        "messages": messages[:8],
        "keywords": keywords,
        "date_quality": date_quality,
        "learning_timeline": learning_timeline,
        "analyst_view": analyst_view,
    }
    viewpoint_comparison = _build_viewpoint_comparison(profile, analyst_view)
    joint_verdict = _build_joint_verdict(profile, analyst_view)
    _persist_profile(conn, stock_row, profile, peers, evidence)

    result = {
        "found": True,
        "stock_code": stock_row["stock_code"],
        "stock_name": stock_row["stock_name"],
        "market": stock_row["market"],
        "market_cap_억": round(float(stock_row["market_cap"] or 0), 1) if stock_row["market_cap"] is not None else None,
        "current_price": latest_price.get("close"),
        "price_date": latest_price.get("date"),
        "sector": stock_row["sector_large"],
        "industry": stock_row["sector_small"] or stock_row["sector_mid"],
        "sector_large": stock_row["sector_large"],
        "sector_mid": stock_row["sector_mid"],
        "sector_small": stock_row["sector_small"],
        "latest_financial": financial,
        "value_chain_position": profile.get("value_chain_position"),
        "business_model": profile.get("business_model"),
        "cycle_type": profile.get("cycle_type"),
        "main_products": profile.get("main_products", []),
        "differentiations": profile.get("differentiations", []),
        "bull_points": profile.get("bull_points", []),
        "bear_points": profile.get("bear_points", []),
        "comparison_summary": profile.get("comparison_summary"),
        "period_comparison_summary": profile.get("period_comparison_summary"),
        "profile": profile,
        "evidence": evidence,
        "date_quality": date_quality,
        "learning_timeline": learning_timeline,
        "analyst_view": analyst_view,
        "viewpoint_comparison": viewpoint_comparison,
        "joint_verdict": joint_verdict,
        "peer_candidates": peers,
        "updated_at": datetime.now().isoformat(),
    }
    result["analysis_as_of"] = _extract_analysis_as_of(result)
    return result


@router.get("/company/{stock_code}")
def get_company_intelligence(stock_code: str):
    conn = connect_stock_db(timeout=15, row_factory=sqlite3.Row)
    try:
        return _compute_company_intelligence(conn, stock_code)
    finally:
        conn.close()


@router.get("/compare")
def compare_companies(codes: str = Query(..., description="comma-separated stock codes")):
    code_list = [c.strip() for c in codes.split(",") if c.strip()]
    conn = connect_stock_db(timeout=15, row_factory=sqlite3.Row)
    try:
        items = [_compute_company_intelligence(conn, code) for code in code_list[:6]]
        rows = [item for item in items if item.get("found")]
        dimensions = [
            "value_chain_position",
            "business_model",
            "cycle_type",
            "main_products",
            "differentiations",
            "bull_points",
            "bear_points",
        ]
        return {"codes": code_list, "items": rows, "dimensions": dimensions}
    finally:
        conn.close()


@router.get("/portfolio/compare")
def compare_portfolio_holdings(limit: int = Query(30, ge=1, le=100)):
    cached = _PORTFOLIO_COMPARE_CACHE.get(limit)
    if cached and time.monotonic() - cached[0] < _PORTFOLIO_COMPARE_CACHE_TTL_SEC:
        return cached[1]
    conn = connect_stock_db(timeout=15, row_factory=sqlite3.Row)
    try:
        holding_rows = conn.execute(
            """
            SELECT stock_code, stock_name, sector, quantity, avg_price, updated_at
            FROM portfolio
            WHERE quantity > 0 AND stock_code IS NOT NULL AND stock_code != ''
            ORDER BY quantity * COALESCE(avg_price, 0) DESC, updated_at DESC
            LIMIT ?
            """,
            (limit,),
        ).fetchall()
        items = []
        summary = {
            "holdings_count": len(holding_rows),
            "with_cherry_profile": 0,
            "with_analyst_coverage": 0,
            "high_overlap": 0,
            "avg_target_upside_positive": 0,
        }
        for row in holding_rows:
            intel = _compute_company_intelligence(conn, str(row["stock_code"]))
            if not intel.get("found"):
                continue
            analyst_view = intel.get("analyst_view") or {}
            comparison = intel.get("viewpoint_comparison") or {}
            current_price = intel.get("current_price")
            avg_target = analyst_view.get("avg_target_price")
            upside_pct = None
            if current_price and avg_target:
                try:
                    upside_pct = round((float(avg_target) - float(current_price)) / float(current_price) * 100, 1)
                except Exception:
                    upside_pct = None
            overlap_count = len(comparison.get("overlap_points") or [])
            item = {
                "stock_code": intel.get("stock_code"),
                "stock_name": intel.get("stock_name"),
                "analysis_as_of": intel.get("analysis_as_of"),
                "sector": intel.get("sector"),
                "industry": intel.get("industry"),
                "quantity": float(row["quantity"] or 0),
                "avg_price": float(row["avg_price"] or 0),
                "current_price": current_price,
                "price_date": intel.get("price_date"),
                "market_cap_억": intel.get("market_cap_억"),
                "value_chain_position": intel.get("value_chain_position"),
                "bull_points": intel.get("bull_points", [])[:3],
                "bear_points": intel.get("bear_points", [])[:2],
                "main_products": intel.get("main_products", [])[:3],
                "analyst_coverage_count": analyst_view.get("consensus_count", 0),
                "analyst_extract_count": analyst_view.get("extract_count", 0),
                "analyst_one_year_report_count": analyst_view.get("one_year_report_count", 0),
                "analyst_one_year_report_read_count": analyst_view.get("one_year_report_read_count", 0),
                "analyst_avg_target_price": avg_target,
                "analyst_target_upside_pct": upside_pct,
                "analyst_positive_themes": analyst_view.get("positive_themes", [])[:4],
                "analyst_risk_themes": analyst_view.get("risk_themes", [])[:4],
                "analyst_one_year_reports": analyst_view.get("one_year_reports", [])[:8],
                "analyst_latest_reports": analyst_view.get("latest_reports", [])[:8],
                "analyst_quarter_trend": analyst_view.get("quarter_trend", [])[:6],
                "analyst_trend_summary": analyst_view.get("trend_summary"),
                "joint_verdict": intel.get("joint_verdict") or {},
                "overlap_points": comparison.get("overlap_points", [])[:3],
                "difference_points": comparison.get("difference_points", [])[:3],
                "period_comparison_summary": intel.get("period_comparison_summary"),
            }
            summary["with_cherry_profile"] += 1
            if item["analyst_coverage_count"] > 0 or item["analyst_extract_count"] > 0:
                summary["with_analyst_coverage"] += 1
            if overlap_count >= 2:
                summary["high_overlap"] += 1
            if upside_pct is not None and upside_pct > 0:
                summary["avg_target_upside_positive"] += 1
            items.append(item)
        items.sort(
            key=lambda item: (
                -(item["analyst_coverage_count"] + item["analyst_extract_count"]),
                -(len(item["overlap_points"])),
                -(item["analyst_target_upside_pct"] if item["analyst_target_upside_pct"] is not None else -9999),
            )
        )
        payload = {
            "as_of": _latest_date_text([item.get("analysis_as_of") for item in items]),
            "summary": summary,
            "items": items,
        }
        _PORTFOLIO_COMPARE_CACHE[limit] = (time.monotonic(), payload)
        return payload
    finally:
        conn.close()


@router.get("/cherry-family/status")
def get_cherry_family_status():
    conn = connect_stock_db(timeout=15, row_factory=sqlite3.Row)
    try:
        _ensure_tables(conn)
        family_ids = [
            "체리형부 25.4Q [25.11.01 ~ 26.1.31]",
            "체리형부 26.1Q [26.02.02 ~ 26.05.30]",
            "체리형부 채널 26.06.01~08.31",
            "Valuefs1",
        ]
        channel_rows = conn.execute(
            """
            SELECT channel_id, channel_name, entity_hint, is_active, last_sync
            FROM telegram_channels
            WHERE channel_id IN ({})
            ORDER BY channel_name, channel_id
            """.format(",".join("?" for _ in family_ids)),
            family_ids,
        ).fetchall()
        channels = []
        message_total = 0
        report_total = 0
        for row in channel_rows:
            msg_count = conn.execute(
                "SELECT COUNT(*) FROM telegram_messages WHERE channel=?",
                (row["channel_id"],),
            ).fetchone()[0]
            report_count = conn.execute(
                "SELECT COUNT(*) FROM report_files WHERE channel_id=?",
                (row["channel_id"],),
            ).fetchone()[0]
            message_total += int(msg_count or 0)
            report_total += int(report_count or 0)
            channels.append(
                {
                    "channel_id": row["channel_id"],
                    "channel_name": row["channel_name"] or row["channel_id"],
                    "entity_hint": row["entity_hint"],
                    "is_active": bool(row["is_active"]),
                    "last_sync": row["last_sync"],
                    "telegram_messages": int(msg_count or 0),
                    "report_files": int(report_count or 0),
                }
            )
        latest_run = conn.execute(
            """
            SELECT *
            FROM cherry_family_learning_runs
            ORDER BY id DESC
            LIMIT 1
            """
        ).fetchone()
        run_payload = None
        if latest_run:
            notes = latest_run["notes_json"]
            try:
                notes = json.loads(notes) if notes else {}
            except Exception:
                notes = {"raw_notes": notes}
            run_payload = dict(latest_run)
            run_payload["notes_json"] = notes
        return {
            "as_of": run_payload.get("completed_at") if run_payload else None,
            "family_channels_expected": len(family_ids),
            "family_channels_registered": len(channel_rows),
            "telegram_message_count": message_total,
            "report_file_count": report_total,
            "channels": channels,
            "latest_learning_run": run_payload,
        }
    finally:
        conn.close()
