#!/usr/bin/env python3
"""Copy the legacy SQLite stock.db into PostgreSQL.

This is a bridge migration, not a hand-written schema redesign. It preserves
table/column names so the application can move one surface at a time.
"""
from __future__ import annotations

import argparse
import os
import sqlite3
from decimal import Decimal
from pathlib import Path
from typing import Iterable

import psycopg
from psycopg import sql

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SQLITE_DB = (ROOT / "stock.db").resolve()
DEFAULT_POSTGRES_URL = os.getenv(
    "POSTGRES_DATABASE_URL",
    os.getenv(
        "DATABASE_URL",
        "postgresql://stock_dashboard:stock_dashboard_local@127.0.0.1:5432/stock_dashboard",
    ),
)
DEFAULT_POSTGRES_URL = DEFAULT_POSTGRES_URL.replace("postgresql+psycopg://", "postgresql://", 1)


def qident(name: str) -> sql.Identifier:
    return sql.Identifier(str(name))


def sqlite_type_to_pg(col_type: str, *, pk: bool, wide_integer: bool = False) -> str:
    t = (col_type or "").upper()
    if pk and "INT" in t:
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    if "INT" in t:
        return "NUMERIC" if wide_integer else "BIGINT"
    if any(x in t for x in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if any(x in t for x in ("NUM", "DEC")):
        return "NUMERIC"
    if "BLOB" in t:
        return "BYTEA"
    if "BOOL" in t:
        return "BOOLEAN"
    return "TEXT"


def table_names(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type='table'
          AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    return [r[0] for r in rows]


def integer_requires_numeric(src: sqlite3.Connection, table: str, column: str) -> bool:
    table_ident = quote_sqlite_ident(table)
    column_ident = quote_sqlite_ident(column)
    row = src.execute(
        f"SELECT {column_ident} FROM {table_ident} "
        f"WHERE typeof({column_ident}) IN ('text','real') AND {column_ident} IS NOT NULL"
    )
    for (value,) in row:
        try:
            parsed = Decimal(str(value).replace(",", "").strip())
        except Exception:
            continue
        if parsed > 9223372036854775807 or parsed < -9223372036854775808:
            return True
    return False


def create_table(pg: psycopg.Connection, src: sqlite3.Connection, table: str, *, drop: bool) -> None:
    cols = src.execute(f"PRAGMA table_info({quote_sqlite_ident(table)})").fetchall()
    if not cols:
        return
    with pg.cursor() as cur:
        if drop:
            cur.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(qident(table)))
        col_defs = []
        table_pk_cols = [c for c in cols if c["pk"]]
        composite_pk = len(table_pk_cols) > 1
        for c in cols:
            name = c["name"]
            pk = bool(c["pk"]) and not composite_pk
            wide_integer = (
                not pk
                and "INT" in (c["type"] or "").upper()
                and integer_requires_numeric(src, table, name)
            )
            pg_type = sqlite_type_to_pg(c["type"], pk=pk, wide_integer=wide_integer)
            nullable = "" if pk or not c["notnull"] else " NOT NULL"
            col_defs.append(sql.SQL("{} {}{}").format(qident(name), sql.SQL(pg_type), sql.SQL(nullable)))
        if composite_pk:
            col_defs.append(
                sql.SQL("PRIMARY KEY ({})").format(
                    sql.SQL(", ").join(qident(c["name"]) for c in table_pk_cols)
                )
            )
        cur.execute(sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(qident(table), sql.SQL(", ").join(col_defs)))


def quote_sqlite_ident(name: str) -> str:
    return '"' + str(name).replace('"', '""') + '"'


def batched(rows: Iterable[sqlite3.Row], size: int) -> Iterable[list[sqlite3.Row]]:
    batch: list[sqlite3.Row] = []
    for row in rows:
        batch.append(row)
        if len(batch) >= size:
            yield batch
            batch = []
    if batch:
        yield batch


def copy_table(pg: psycopg.Connection, src: sqlite3.Connection, table: str, *, batch_size: int) -> int:
    cols = src.execute(f"PRAGMA table_info({quote_sqlite_ident(table)})").fetchall()
    col_names = [c["name"] for c in cols]
    bool_cols = {c["name"] for c in cols if "BOOL" in (c["type"] or "").upper()}
    int_cols = {c["name"] for c in cols if "INT" in (c["type"] or "").upper()}
    wide_int_cols = {c for c in int_cols if integer_requires_numeric(src, table, c)}
    float_cols = {
        c["name"]
        for c in cols
        if any(x in (c["type"] or "").upper() for x in ("REAL", "FLOA", "DOUB", "NUM", "DEC"))
    }
    if not col_names:
        return 0
    placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in col_names)
    insert_stmt = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
        qident(table),
        sql.SQL(", ").join(qident(c) for c in col_names),
        placeholders,
    )
    total = 0
    rows = src.execute(sqlite_select_all(table))
    with pg.cursor() as cur:
        for batch in batched(rows, batch_size):
            payload = []
            for row in batch:
                values = []
                for c in col_names:
                    v = row[c]
                    if c in bool_cols and v is not None:
                        v = bool(v)
                    elif c in wide_int_cols and v is not None:
                        v = Decimal(str(v).replace(",", "").strip())
                    elif c in int_cols and isinstance(v, str):
                        v = int(float(v.replace(",", "").strip()))
                    elif c in float_cols and isinstance(v, str):
                        v = float(v.replace(",", "").strip())
                    values.append(v)
                payload.append(tuple(values))
            cur.executemany(insert_stmt, payload)
            total += len(payload)
    return total


def sqlite_select_all(table: str) -> str:
    return f"SELECT * FROM {quote_sqlite_ident(table)}"


def reset_identity(pg: psycopg.Connection, table: str, src: sqlite3.Connection) -> None:
    pk_rows = src.execute(f"PRAGMA table_info({quote_sqlite_ident(table)})").fetchall()
    single_int_pk = [r for r in pk_rows if r["pk"] == 1 and "INT" in (r["type"] or "").upper()]
    if len(single_int_pk) != 1:
        return
    pk_col = single_int_pk[0]["name"]
    with pg.cursor() as cur:
        cur.execute(
            sql.SQL(
                "SELECT setval(pg_get_serial_sequence(%s, %s), "
                "COALESCE((SELECT MAX({}) FROM {}), 1), true)"
            ).format(qident(pk_col), qident(table)),
            (table, pk_col),
        )


def migrate(sqlite_db: Path, postgres_url: str, *, drop: bool, only: list[str], batch_size: int) -> None:
    src = sqlite3.connect(str(sqlite_db))
    src.row_factory = sqlite3.Row
    try:
        names = table_names(src)
        if only:
            wanted = set(only)
            names = [n for n in names if n in wanted]
        with psycopg.connect(postgres_url) as pg:
            pg.execute("SET TIME ZONE 'Asia/Seoul'")
            for table in names:
                create_table(pg, src, table, drop=drop)
            pg.commit()
            for i, table in enumerate(names, start=1):
                count = copy_table(pg, src, table, batch_size=batch_size)
                reset_identity(pg, table, src)
                pg.commit()
                print(f"[{i}/{len(names)}] {table}: {count:,} rows")
    finally:
        src.close()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sqlite-db", type=Path, default=DEFAULT_SQLITE_DB)
    parser.add_argument("--postgres-url", default=DEFAULT_POSTGRES_URL)
    parser.add_argument("--drop", action="store_true", help="Drop target tables before recreating them")
    parser.add_argument("--only", nargs="*", default=[], help="Migrate only these table names")
    parser.add_argument("--batch-size", type=int, default=5000)
    args = parser.parse_args()
    migrate(args.sqlite_db.resolve(), args.postgres_url, drop=args.drop, only=args.only, batch_size=args.batch_size)


if __name__ == "__main__":
    main()
