#!/usr/bin/env python3
"""Migration for ``is_standalone_derivation`` (PostgreSQL-only, idempotent).

This table is the 3-layer provenance store (raw / computed / evidence) used by
``scripts/is_standalone_pipeline.py`` for the income-statement 당분기(standalone)
derivation.  It is created ONLY in the PostgreSQL primary — it is not part of the
legacy SQLite schema and must never be opened through a raw SQLite connection.

Modes:
  (default)        read-only existence check (no writes)
  --apply          CREATE TABLE IF NOT EXISTS (idempotent; commit)
  --rollback       DROP TABLE IF EXISTS (rollback; commit)

Usage:
  python3 scripts/migrate_is_standalone_derivation.py            # check only
  python3 scripts/migrate_is_standalone_derivation.py --apply     # forward
  python3 scripts/migrate_is_standalone_derivation.py --rollback  # backward
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from db_compat import connect_primary_db

TABLE = "is_standalone_derivation"

# Native PostgreSQL DDL.  Types mirror ``financial_fix_log`` (DOUBLE PRECISION
# for REAL values — never PG ``REAL``/float4, which would silently drop ~8
# significant digits from large 원-denominated facts).
DDL = f"""
CREATE TABLE IF NOT EXISTS {TABLE} (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_code       TEXT,
  year             INTEGER,
  quarter          INTEGER,
  field            TEXT,
  mode             TEXT NOT NULL,
  raw_value        DOUBLE PRECISION,
  prior_raw_value  DOUBLE PRECISION,
  computed_value   DOUBLE PRECISION,
  acode            TEXT,
  adecimal         INTEGER,
  consolidated     INTEGER,
  period_token     TEXT,
  suffix           TEXT,
  skip_reason      TEXT,
  rcept_no         TEXT,
  run_id           TEXT,
  created_at       TEXT
)
"""


def _exists(conn) -> bool:
    row = conn.execute(
        "SELECT to_regclass('public." + TABLE + "')"
    ).fetchone()
    return row is not None and row[0] is not None


def check() -> int:
    conn = connect_primary_db(readonly=True, timeout=60)
    try:
        present = _exists(conn)
        print(f"[check] {TABLE}: {'EXISTS' if present else 'MISSING'}")
        if present:
            n = conn.execute(f"SELECT COUNT(*) FROM {TABLE}").fetchone()[0]
            print(f"[check] {TABLE} rows = {n}")
        return 0 if present else 1
    finally:
        conn.close()


def apply() -> int:
    conn = connect_primary_db(readonly=False, timeout=120)
    try:
        if _exists(conn):
            print(f"[apply] {TABLE} already exists — no-op (idempotent).")
        else:
            conn.execute(DDL)
            conn.commit()
            print(f"[apply] {TABLE} created.")
        return 0
    except Exception as exc:  # noqa: BLE001 — report and rollback
        conn.rollback()
        print(f"[apply] FAILED: {exc}")
        return 2
    finally:
        conn.close()


def rollback() -> int:
    conn = connect_primary_db(readonly=False, timeout=120)
    try:
        if not _exists(conn):
            print(f"[rollback] {TABLE} does not exist — no-op (idempotent).")
        else:
            conn.execute(f"DROP TABLE IF EXISTS {TABLE}")
            conn.commit()
            print(f"[rollback] {TABLE} dropped.")
        return 0
    except Exception as exc:  # noqa: BLE001
        conn.rollback()
        print(f"[rollback] FAILED: {exc}")
        return 2
    finally:
        conn.close()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--apply", action="store_true", help="create table")
    group.add_argument("--rollback", action="store_true", help="drop table")
    args = parser.parse_args()
    if args.apply:
        return apply()
    if args.rollback:
        return rollback()
    return check()


if __name__ == "__main__":
    raise SystemExit(main())
