#!/usr/bin/env python3
"""Stage the operational SQLite dataset in PostgreSQL and verify it before cutover.

The migration is intentionally schema-isolated. It never mutates ``public``
unless ``--cutover`` is explicitly supplied after a successful verification.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sqlite3
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql
from psycopg.errors import UniqueViolation

ROOT = Path(__file__).resolve().parents[1]
SQLITE_DB = (ROOT / "stock.db").resolve()
STATE_DIR = ROOT / "research_outputs" / "postgres_cutover"
DEFAULT_SCHEMA = "cutover_20260810"

if str(ROOT) not in os.sys.path:
    os.sys.path.insert(0, str(ROOT))
from config import DATABASE_URL  # noqa: E402

POSTGRES_URL = DATABASE_URL.replace("postgresql+psycopg://", "postgresql://", 1)


def is_archive_table(name: str) -> bool:
    value = name.lower()
    return bool(
        value.startswith("_")
        or "backup" in value
        or value.startswith("lost_and_found")
        or value in {"data_lock"}
    )


def quote_sqlite(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def table_names(src: sqlite3.Connection) -> list[str]:
    rows = src.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return [row[0] for row in rows if not is_archive_table(row[0])]


def pg_type(declared: str, *, primary_key: bool) -> str:
    value = (declared or "").upper()
    if primary_key and "INT" in value:
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    if "INT" in value:
        # NUMERIC accepts legacy values that exceeded signed bigint or were stored as text.
        return "NUMERIC"
    if any(token in value for token in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if any(token in value for token in ("NUM", "DEC")):
        return "NUMERIC"
    if "BLOB" in value:
        return "BYTEA"
    if "BOOL" in value:
        return "BOOLEAN"
    return "TEXT"


def convert(value: Any, declared: str) -> Any:
    if value is None:
        return None
    kind = (declared or "").upper()
    if "BOOL" in kind:
        return bool(value)
    if "INT" in kind:
        try:
            return Decimal(str(value).replace(",", "").strip())
        except Exception:
            return None
    if any(token in kind for token in ("REAL", "FLOA", "DOUB", "NUM", "DEC")):
        try:
            return Decimal(str(value).replace(",", "").strip())
        except Exception:
            return None
    if isinstance(value, str):
        # SQLite accepts embedded NULs in TEXT; PostgreSQL deliberately rejects them.
        return value.replace("\x00", "")
    return value


def create_table(
    src: sqlite3.Connection,
    pg: psycopg.Connection,
    schema: str,
    table: str,
) -> list[sqlite3.Row]:
    columns = src.execute(f"PRAGMA table_info({quote_sqlite(table)})").fetchall()
    pk_columns = sorted((row for row in columns if row["pk"]), key=lambda row: row["pk"])
    pk_has_null = any(
        src.execute(
            f"SELECT 1 FROM {quote_sqlite(table)} WHERE {quote_sqlite(row['name'])} IS NULL LIMIT 1"
        ).fetchone()
        for row in pk_columns
    )
    enforce_pk = bool(pk_columns) and not pk_has_null
    composite_pk = len(pk_columns) > 1
    if pk_has_null:
        print(f"WARNING {table}: nullable SQLite primary key not enforced in PostgreSQL", flush=True)
    definitions = []
    for row in columns:
        single_pk = bool(row["pk"]) and not composite_pk and enforce_pk
        definition = sql.SQL("{} {}").format(
            sql.Identifier(row["name"]), sql.SQL(pg_type(row["type"], primary_key=single_pk))
        )
        # Legacy SQLite files can contain NULLs in columns later declared NOT
        # NULL (for example after ALTER/rebuild workflows). Preserve source rows;
        # only primary keys are enforced during the bridge cutover.
        if single_pk:
            definition += sql.SQL(" NOT NULL")
        definitions.append(definition)
    if enforce_pk:
        definitions.append(
            sql.SQL("PRIMARY KEY ({})").format(
                sql.SQL(", ").join(sql.Identifier(row["name"]) for row in pk_columns)
            )
        )
    pg.execute(sql.SQL("DROP TABLE IF EXISTS {}.{} CASCADE").format(
        sql.Identifier(schema), sql.Identifier(table)
    ))
    pg.execute(sql.SQL("CREATE TABLE {}.{} ({})").format(
        sql.Identifier(schema), sql.Identifier(table), sql.SQL(", ").join(definitions)
    ))
    return columns


def copy_table(
    src: sqlite3.Connection,
    pg: psycopg.Connection,
    schema: str,
    table: str,
) -> int:
    columns = create_table(src, pg, schema, table)
    names = [row["name"] for row in columns]
    declared = {row["name"]: row["type"] for row in columns}
    statement = sql.SQL("COPY {}.{} ({}) FROM STDIN").format(
        sql.Identifier(schema), sql.Identifier(table),
        sql.SQL(", ").join(sql.Identifier(name) for name in names),
    )
    count = 0
    rows = src.execute(f"SELECT * FROM {quote_sqlite(table)}")
    with pg.cursor().copy(statement) as copy:
        for row in rows:
            copy.write_row(tuple(convert(row[name], declared[name]) for name in names))
            count += 1
    reset_identity(pg, schema, table, columns)
    return count


def reset_identity(
    pg: psycopg.Connection, schema: str, table: str, columns: list[sqlite3.Row]
) -> None:
    ids = [row for row in columns if row["pk"] == 1 and "INT" in (row["type"] or "").upper()]
    if len(ids) != 1:
        return
    column = ids[0]["name"]
    pg.execute(
        sql.SQL(
            "SELECT setval(pg_get_serial_sequence(%s,%s), "
            "GREATEST(COALESCE((SELECT MAX({}) FROM {}.{}),1),1), true)"
        ).format(sql.Identifier(column), sql.Identifier(schema), sql.Identifier(table)),
        (f"{schema}.{table}", column),
    )


def create_indexes(
    src: sqlite3.Connection, pg: psycopg.Connection, schema: str, table: str
) -> list[str]:
    created = []
    for index in src.execute(f"PRAGMA index_list({quote_sqlite(table)})"):
        name = index[1]
        unique = bool(index[2])
        origin = index[3] if len(index) > 3 else "c"
        partial = bool(index[4]) if len(index) > 4 else False
        if origin == "pk" or partial:
            continue
        columns = [row[2] for row in src.execute(f"PRAGMA index_info({quote_sqlite(name)})") if row[2]]
        if not columns:
            continue
        # Index names are schema-wide in PostgreSQL; prefix prevents collisions.
        pg_name = f"ix_{table}_{hashlib.sha1(name.encode()).hexdigest()[:10]}"[:63]
        statement = sql.SQL("CREATE {} INDEX {} ON {}.{} ({})").format(
            sql.SQL("UNIQUE" if unique else ""), sql.Identifier(pg_name),
            sql.Identifier(schema), sql.Identifier(table),
            sql.SQL(", ").join(sql.Identifier(column) for column in columns),
        )
        try:
            with pg.transaction():
                pg.execute(statement)
        except UniqueViolation:
            # Some legacy tables contain rows predating a later-declared unique
            # index. Preserve all rows and retain lookup performance; deduplication
            # is a separate, explicit data-quality decision.
            fallback_name = (pg_name + "_nonunique")[:63]
            pg.execute(sql.SQL("CREATE INDEX {} ON {}.{} ({})").format(
                sql.Identifier(fallback_name), sql.Identifier(schema),
                sql.Identifier(table),
                sql.SQL(", ").join(sql.Identifier(column) for column in columns),
            ))
            print(
                f"WARNING {table}.{name}: duplicate rows; unique index downgraded",
                flush=True,
            )
            pg_name = fallback_name
        created.append(pg_name)
    return created


def verify_counts(
    src: sqlite3.Connection, pg: psycopg.Connection, schema: str, tables: list[str]
) -> dict:
    rows = []
    failures = []
    for table in tables:
        sqlite_count = src.execute(
            f"SELECT COUNT(*) FROM {quote_sqlite(table)}"
        ).fetchone()[0]
        postgres_count = pg.execute(
            sql.SQL("SELECT COUNT(*) FROM {}.{}").format(
                sql.Identifier(schema), sql.Identifier(table)
            )
        ).fetchone()[0]
        item = {
            "table": table,
            "sqlite_count": sqlite_count,
            "postgres_count": postgres_count,
            "match": sqlite_count == postgres_count,
        }
        rows.append(item)
        if not item["match"]:
            failures.append(item)
    return {"ok": not failures, "tables": rows, "failures": failures}


def cutover(pg: psycopg.Connection, schema: str, backup_schema: str) -> None:
    exists = pg.execute(
        "SELECT 1 FROM information_schema.schemata WHERE schema_name=%s", (backup_schema,)
    ).fetchone()
    if exists:
        raise RuntimeError(f"backup schema already exists: {backup_schema}")
    pg.execute(sql.SQL("ALTER SCHEMA public RENAME TO {}").format(sql.Identifier(backup_schema)))
    pg.execute(sql.SQL("ALTER SCHEMA {} RENAME TO public").format(sql.Identifier(schema)))
    pg.execute("GRANT USAGE, CREATE ON SCHEMA public TO PUBLIC")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", default=DEFAULT_SCHEMA)
    parser.add_argument("--only", nargs="*", default=[])
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--verify-only", action="store_true")
    parser.add_argument("--cutover", action="store_true")
    args = parser.parse_args()
    if not re.fullmatch(r"[a-z][a-z0-9_]{0,62}", args.schema):
        raise SystemExit("invalid schema name")
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    manifest_path = STATE_DIR / f"{args.schema}.json"
    state = json.loads(manifest_path.read_text()) if args.resume and manifest_path.exists() else {
        "schema": args.schema, "started_at": datetime.now().isoformat(), "completed": {}
    }
    src = sqlite3.connect(f"file:{SQLITE_DB}?mode=ro", uri=True, timeout=120)
    src.row_factory = sqlite3.Row
    tables = table_names(src)
    if args.only:
        wanted = set(args.only)
        tables = [table for table in tables if table in wanted]
    with psycopg.connect(POSTGRES_URL) as pg:
        pg.execute("SET TIME ZONE 'Asia/Seoul'")
        pg.execute("SET synchronous_commit TO off")
        pg.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(args.schema)))
        pg.commit()
        if not args.verify_only:
            for index, table in enumerate(tables, 1):
                if args.resume and table in state["completed"]:
                    continue
                count = copy_table(src, pg, args.schema, table)
                indexes = create_indexes(src, pg, args.schema, table)
                pg.execute(sql.SQL("ANALYZE {}.{}").format(
                    sql.Identifier(args.schema), sql.Identifier(table)
                ))
                pg.commit()
                state["completed"][table] = {"rows": count, "indexes": len(indexes)}
                manifest_path.write_text(json.dumps(state, ensure_ascii=False, indent=2))
                print(f"[{index}/{len(tables)}] {table}: {count:,} rows / {len(indexes)} indexes", flush=True)
        verification = verify_counts(src, pg, args.schema, tables)
        state["verification"] = verification
        state["verified_at"] = datetime.now().isoformat()
        manifest_path.write_text(json.dumps(state, ensure_ascii=False, indent=2))
        print(json.dumps({"ok": verification["ok"], "failures": verification["failures"]}, ensure_ascii=False))
        if args.cutover:
            if not verification["ok"]:
                raise SystemExit("cutover blocked: row-count verification failed")
            backup = "pre_cutover_" + datetime.now().strftime("%Y%m%d_%H%M%S")
            cutover(pg, args.schema, backup)
            pg.commit()
            state["cutover"] = {"at": datetime.now().isoformat(), "backup_schema": backup}
            manifest_path.write_text(json.dumps(state, ensure_ascii=False, indent=2))
            print(json.dumps(state["cutover"], ensure_ascii=False))
    src.close()


if __name__ == "__main__":
    main()
